# Generated by Django 4.0.6 on 2023-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=1000)),
                ('project_description', models.CharField(max_length=10000)),
                ('project_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_Lang', models.CharField(max_length=1000)),
                ('skill_Img', models.ImageField(upload_to='')),
                ('skill_Library_1', models.CharField(max_length=1000)),
                ('skill_Library_2', models.CharField(max_length=1000)),
                ('skill_Library_3', models.CharField(max_length=1000)),
                ('skill_Library_4', models.CharField(max_length=1000)),
                ('skill_certificate_link', models.URLField()),
                ('skill_certificate_logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
