# Generated by Django 4.0.6 on 2023-04-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='skill_Library_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='skill_Library_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='skill_Library_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='skill_Library_4',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
