# Generated by Django 4.0.6 on 2023-04-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_alter_userinfo_skill_library_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_description',
            new_name='projectdescription',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_name',
            new_name='projectname',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_photo',
            new_name='projectphoto',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='skill_Img',
            new_name='skillImg',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='skill_Lang',
            new_name='skillLang',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='skill_Library_1',
            new_name='skillLibrary_1',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='skill_Library_2',
            new_name='skillLibrary_2',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='skill_Library_3',
            new_name='skillLibrary_3',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='skill_Library_4',
            new_name='skillLibrary_4',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='skill_certificate_link',
            new_name='skillcertificate_link',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='skill_certificate_logo',
            new_name='skillcertificate_logo',
        ),
    ]
