# Generated by Django 4.0.6 on 2023-04-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_rename_project_description_projects_projectdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='skillcertificate_organiser',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
