# Generated by Django 4.0.6 on 2023-04-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_userinfo_skillcertificate_organiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='skillcertificate_link',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='skillcertificate_logo',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='skillcertificate_organiser',
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillcertificate_link', models.URLField()),
                ('skillcertificate_logo', models.ImageField(upload_to='')),
                ('skillcertificate_organiser', models.CharField(blank=True, max_length=1000)),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.userinfo')),
            ],
        ),
    ]
