# Generated by Django 4.0.6 on 2023-04-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_rename_skillcertificate_link_1_certificates_skillcertificate_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projectdescription',
            field=models.TextField(max_length=10000),
        ),
    ]
