# Generated by Django 4.0.6 on 2023-04-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_alter_projects_projectdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projecturl',
            field=models.URLField(blank=True),
        ),
    ]
